### ISSUE TITLE
Ubuntu 18.04 Desktop - Gtk-Message: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by WilliamCocker** [lcherone/LXD-UI#5]
Hi,

This LXD UI looks awesome. I can't get the appimage to launch on Ubuntu 18.04 Desktop (kernel 4.15.0-22-generic) with LXD snap v3.1 installed.

I get an error message at launch:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
```
Then the UI appears and tries to refresh forever...

Let me know if I can try something to get it to work. Thanks.

**Comment by lcherone** [comment]
How are you launching it?

[Electron](https://electronjs.org/) does have some dependencies, I'm not sure what all of them are and I can't remember what but I had to install something on a fresh XFCE desktop.

Guess GNOME needs GTK+ ones :/

**Try running:**

`sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`

Let me know if that fixes it.

**Comment by WilliamCocker** [comment]
I've installed the dependencies and now the gui is all white and the lxdui process uses a single processor core at 100%...

**Comment by lcherone** [comment]
Open the dev tools `Ctrl-i`, is there anything in the console?

**Comment by WilliamCocker** [comment]
Not a thing, every tab is empty and CPU usage remains at 100%... nothing in journalctl either.

**Comment by lcherone** [comment]
Sorry, I'm not sure what it could be, if you getting nothing, even in `Elements` section and its 100% CPU then its to do with electron.  

Your need to look into if the issue is with 18.04 by installing some other electron based apps. I did a quick google and found there is an issue with libcurl in 18.04. But LXD-UI does not use curl.. it only uses nodes `os`,  `child_process` and most likely `fs` via the electron-store package. Rest is just plain old vue/css etc...

**Comment by WilliamCocker** [comment]
Alright thanks for trying. I'll get back to this machine on Friday and try Atom, I'll let you know then.

**Comment by WilliamCocker** [comment]
Ok Atom is behaving weirdly as well, I guess I'll wait for Electron to be 18.04 aware... Thanks anyway.

**Comment by nebi19** [comment]
that is also my question.

**Comment by lcherone** [comment]
@nebi19 Can you open another issue and include the full details of what's happening.. cheers
